apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build
spec:
  entrypoint: build
  volumeClaimTemplates:
  - metadata:
      name: code
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 64Mi
        
  templates:
  - name: build
    steps:
    - - name: clone
        template: git-clone
    - - name: push
        template: kaniko
  - name: git-clone
    container:
      image: k8s.gcr.io/git-sync/git-sync:v3.1.7
      command: ["/git-sync"]
      args: [
        "--one-time",
        "--depth", "1",
        "--dest", "podinfo",
        "--repo", "https://github.com/fterrag/go-docker-example.git",
        "--branch", "master"]
      volumeMounts:
        - name: code
          mountPath: /tmp/git
  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:debug
      # command: ["ls","-l","/tmp/git/podinfo"]
      command: ["/kaniko/executor"]
      args: [ 
        "--insecure",
        "--dockerfile=Dockerfile",
        "--context=/tmp/git/podinfo",
        "--destination=registry-docker-registry.registry:5000/podinfo:latest"]
      volumeMounts:
        - name: code
          mountPath: /tmp/git
